package com.uxiaoxi.ym.appserver.db.cluster.dto;

import java.io.Serializable;
import java.util.Date;

public class Cluster implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster.id
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster.title
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster.create_dt
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    private Date createDt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster.create_by
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    private Long createBy;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster.face
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    private String face;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster.school
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    private String school;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster.province
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    private String province;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster.city
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    private String city;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster.district
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    private String district;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster.sn
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    private String sn;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster.longitude
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    private String longitude;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster.latitude
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    private String latitude;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table cluster
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster.id
     * @return  the value of cluster.id
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster.id
     * @param id  the value for cluster.id
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster.title
     * @return  the value of cluster.title
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster.title
     * @param title  the value for cluster.title
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster.create_dt
     * @return  the value of cluster.create_dt
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster.create_dt
     * @param createDt  the value for cluster.create_dt
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster.create_by
     * @return  the value of cluster.create_by
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster.create_by
     * @param createBy  the value for cluster.create_by
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster.face
     * @return  the value of cluster.face
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster.face
     * @param face  the value for cluster.face
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public void setFace(String face) {
        this.face = face == null ? null : face.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster.school
     * @return  the value of cluster.school
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster.school
     * @param school  the value for cluster.school
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster.province
     * @return  the value of cluster.province
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster.province
     * @param province  the value for cluster.province
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster.city
     * @return  the value of cluster.city
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster.city
     * @param city  the value for cluster.city
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster.district
     * @return  the value of cluster.district
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster.district
     * @param district  the value for cluster.district
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster.sn
     * @return  the value of cluster.sn
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster.sn
     * @param sn  the value for cluster.sn
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster.longitude
     * @return  the value of cluster.longitude
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster.longitude
     * @param longitude  the value for cluster.longitude
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster.latitude
     * @return  the value of cluster.latitude
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster.latitude
     * @param latitude  the value for cluster.latitude
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Cluster other = (Cluster) that;
        return (this.getId() == null ? other.getId() == null : this.getId()
                .equals(other.getId()))
                && (this.getTitle() == null ? other.getTitle() == null : this
                        .getTitle().equals(other.getTitle()))
                && (this.getCreateDt() == null ? other.getCreateDt() == null
                        : this.getCreateDt().equals(other.getCreateDt()))
                && (this.getCreateBy() == null ? other.getCreateBy() == null
                        : this.getCreateBy().equals(other.getCreateBy()))
                && (this.getFace() == null ? other.getFace() == null : this
                        .getFace().equals(other.getFace()))
                && (this.getSchool() == null ? other.getSchool() == null : this
                        .getSchool().equals(other.getSchool()))
                && (this.getProvince() == null ? other.getProvince() == null
                        : this.getProvince().equals(other.getProvince()))
                && (this.getCity() == null ? other.getCity() == null : this
                        .getCity().equals(other.getCity()))
                && (this.getDistrict() == null ? other.getDistrict() == null
                        : this.getDistrict().equals(other.getDistrict()))
                && (this.getSn() == null ? other.getSn() == null : this.getSn()
                        .equals(other.getSn()))
                && (this.getLongitude() == null ? other.getLongitude() == null
                        : this.getLongitude().equals(other.getLongitude()))
                && (this.getLatitude() == null ? other.getLatitude() == null
                        : this.getLatitude().equals(other.getLatitude()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result
                + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result
                + ((getCreateDt() == null) ? 0 : getCreateDt().hashCode());
        result = prime * result
                + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result
                + ((getFace() == null) ? 0 : getFace().hashCode());
        result = prime * result
                + ((getSchool() == null) ? 0 : getSchool().hashCode());
        result = prime * result
                + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result
                + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result
                + ((getDistrict() == null) ? 0 : getDistrict().hashCode());
        result = prime * result + ((getSn() == null) ? 0 : getSn().hashCode());
        result = prime * result
                + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result
                + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Sat Jan 30 20:07:36 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", createDt=").append(createDt);
        sb.append(", createBy=").append(createBy);
        sb.append(", face=").append(face);
        sb.append(", school=").append(school);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", district=").append(district);
        sb.append(", sn=").append(sn);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append("]");
        return sb.toString();
    }
}