package com.uxiaoxi.ym.appserver.db.cluster.dto;

import java.io.Serializable;
import java.util.Date;

public class ClusterUser implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster_user.id
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster_user.acc_id
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    private Long accId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster_user.clu_id
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    private Long cluId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster_user.acc_name
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    private String accName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster_user.msg_flg
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    private Integer msgFlg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster_user.acc_type
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    private Integer accType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster_user.child_name
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    private String childName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cluster_user.create_dt
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    private Date createDt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table cluster_user
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster_user.id
     * @return  the value of cluster_user.id
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster_user.id
     * @param id  the value for cluster_user.id
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster_user.acc_id
     * @return  the value of cluster_user.acc_id
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public Long getAccId() {
        return accId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster_user.acc_id
     * @param accId  the value for cluster_user.acc_id
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public void setAccId(Long accId) {
        this.accId = accId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster_user.clu_id
     * @return  the value of cluster_user.clu_id
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public Long getCluId() {
        return cluId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster_user.clu_id
     * @param cluId  the value for cluster_user.clu_id
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public void setCluId(Long cluId) {
        this.cluId = cluId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster_user.acc_name
     * @return  the value of cluster_user.acc_name
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public String getAccName() {
        return accName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster_user.acc_name
     * @param accName  the value for cluster_user.acc_name
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public void setAccName(String accName) {
        this.accName = accName == null ? null : accName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster_user.msg_flg
     * @return  the value of cluster_user.msg_flg
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public Integer getMsgFlg() {
        return msgFlg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster_user.msg_flg
     * @param msgFlg  the value for cluster_user.msg_flg
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public void setMsgFlg(Integer msgFlg) {
        this.msgFlg = msgFlg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster_user.acc_type
     * @return  the value of cluster_user.acc_type
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public Integer getAccType() {
        return accType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster_user.acc_type
     * @param accType  the value for cluster_user.acc_type
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public void setAccType(Integer accType) {
        this.accType = accType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster_user.child_name
     * @return  the value of cluster_user.child_name
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public String getChildName() {
        return childName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster_user.child_name
     * @param childName  the value for cluster_user.child_name
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public void setChildName(String childName) {
        this.childName = childName == null ? null : childName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cluster_user.create_dt
     * @return  the value of cluster_user.create_dt
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cluster_user.create_dt
     * @param createDt  the value for cluster_user.create_dt
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ClusterUser other = (ClusterUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId()
                .equals(other.getId()))
                && (this.getAccId() == null ? other.getAccId() == null : this
                        .getAccId().equals(other.getAccId()))
                && (this.getCluId() == null ? other.getCluId() == null : this
                        .getCluId().equals(other.getCluId()))
                && (this.getAccName() == null ? other.getAccName() == null
                        : this.getAccName().equals(other.getAccName()))
                && (this.getMsgFlg() == null ? other.getMsgFlg() == null : this
                        .getMsgFlg().equals(other.getMsgFlg()))
                && (this.getAccType() == null ? other.getAccType() == null
                        : this.getAccType().equals(other.getAccType()))
                && (this.getChildName() == null ? other.getChildName() == null
                        : this.getChildName().equals(other.getChildName()))
                && (this.getCreateDt() == null ? other.getCreateDt() == null
                        : this.getCreateDt().equals(other.getCreateDt()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result
                + ((getAccId() == null) ? 0 : getAccId().hashCode());
        result = prime * result
                + ((getCluId() == null) ? 0 : getCluId().hashCode());
        result = prime * result
                + ((getAccName() == null) ? 0 : getAccName().hashCode());
        result = prime * result
                + ((getMsgFlg() == null) ? 0 : getMsgFlg().hashCode());
        result = prime * result
                + ((getAccType() == null) ? 0 : getAccType().hashCode());
        result = prime * result
                + ((getChildName() == null) ? 0 : getChildName().hashCode());
        result = prime * result
                + ((getCreateDt() == null) ? 0 : getCreateDt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Mar 09 20:24:35 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accId=").append(accId);
        sb.append(", cluId=").append(cluId);
        sb.append(", accName=").append(accName);
        sb.append(", msgFlg=").append(msgFlg);
        sb.append(", accType=").append(accType);
        sb.append(", childName=").append(childName);
        sb.append(", createDt=").append(createDt);
        sb.append("]");
        return sb.toString();
    }
}