package com.uxiaoxi.ym.appserver.db.cluster.dto;

import java.io.Serializable;
import java.util.Date;

public class Remark implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column remark.id
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column remark.acc_id
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    private Long accId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column remark.acc_id_obj
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    private Long accIdObj;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column remark.clu_id
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    private Long cluId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column remark.remark
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    private String remark;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column remark.create_dt
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    private Date createDt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column remark.id
     * @return  the value of remark.id
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column remark.id
     * @param id  the value for remark.id
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column remark.acc_id
     * @return  the value of remark.acc_id
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    public Long getAccId() {
        return accId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column remark.acc_id
     * @param accId  the value for remark.acc_id
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    public void setAccId(Long accId) {
        this.accId = accId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column remark.acc_id_obj
     * @return  the value of remark.acc_id_obj
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    public Long getAccIdObj() {
        return accIdObj;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column remark.acc_id_obj
     * @param accIdObj  the value for remark.acc_id_obj
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    public void setAccIdObj(Long accIdObj) {
        this.accIdObj = accIdObj;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column remark.clu_id
     * @return  the value of remark.clu_id
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    public Long getCluId() {
        return cluId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column remark.clu_id
     * @param cluId  the value for remark.clu_id
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    public void setCluId(Long cluId) {
        this.cluId = cluId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column remark.remark
     * @return  the value of remark.remark
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column remark.remark
     * @param remark  the value for remark.remark
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column remark.create_dt
     * @return  the value of remark.create_dt
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column remark.create_dt
     * @param createDt  the value for remark.create_dt
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Remark other = (Remark) that;
        return (this.getId() == null ? other.getId() == null : this.getId()
                .equals(other.getId()))
                && (this.getAccId() == null ? other.getAccId() == null : this
                        .getAccId().equals(other.getAccId()))
                && (this.getAccIdObj() == null ? other.getAccIdObj() == null
                        : this.getAccIdObj().equals(other.getAccIdObj()))
                && (this.getCluId() == null ? other.getCluId() == null : this
                        .getCluId().equals(other.getCluId()))
                && (this.getRemark() == null ? other.getRemark() == null : this
                        .getRemark().equals(other.getRemark()))
                && (this.getCreateDt() == null ? other.getCreateDt() == null
                        : this.getCreateDt().equals(other.getCreateDt()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result
                + ((getAccId() == null) ? 0 : getAccId().hashCode());
        result = prime * result
                + ((getAccIdObj() == null) ? 0 : getAccIdObj().hashCode());
        result = prime * result
                + ((getCluId() == null) ? 0 : getCluId().hashCode());
        result = prime * result
                + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result
                + ((getCreateDt() == null) ? 0 : getCreateDt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 18:31:14 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accId=").append(accId);
        sb.append(", accIdObj=").append(accIdObj);
        sb.append(", cluId=").append(cluId);
        sb.append(", remark=").append(remark);
        sb.append(", createDt=").append(createDt);
        sb.append("]");
        return sb.toString();
    }
}