package com.uxiaoxi.ym.appserver.db.msg.dto;

import java.io.Serializable;
import java.util.Date;

public class Msg implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg.id
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg.sender_id
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    private Long senderId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg.clu_id
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    private Long cluId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg.msg_type
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    private Long msgType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg.content
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    private String content;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg.content_type
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    private Long contentType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg.url
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg.stype
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    private Integer stype;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg.select1
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    private String select1;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg.select2
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    private String select2;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg.create_at
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    private Date createAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg.id
     * @return  the value of msg.id
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg.id
     * @param id  the value for msg.id
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg.sender_id
     * @return  the value of msg.sender_id
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public Long getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg.sender_id
     * @param senderId  the value for msg.sender_id
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public void setSenderId(Long senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg.clu_id
     * @return  the value of msg.clu_id
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public Long getCluId() {
        return cluId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg.clu_id
     * @param cluId  the value for msg.clu_id
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public void setCluId(Long cluId) {
        this.cluId = cluId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg.msg_type
     * @return  the value of msg.msg_type
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public Long getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg.msg_type
     * @param msgType  the value for msg.msg_type
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public void setMsgType(Long msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg.content
     * @return  the value of msg.content
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg.content
     * @param content  the value for msg.content
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg.content_type
     * @return  the value of msg.content_type
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public Long getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg.content_type
     * @param contentType  the value for msg.content_type
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public void setContentType(Long contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg.url
     * @return  the value of msg.url
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg.url
     * @param url  the value for msg.url
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg.stype
     * @return  the value of msg.stype
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public Integer getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg.stype
     * @param stype  the value for msg.stype
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public void setStype(Integer stype) {
        this.stype = stype;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg.select1
     * @return  the value of msg.select1
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public String getSelect1() {
        return select1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg.select1
     * @param select1  the value for msg.select1
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public void setSelect1(String select1) {
        this.select1 = select1 == null ? null : select1.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg.select2
     * @return  the value of msg.select2
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public String getSelect2() {
        return select2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg.select2
     * @param select2  the value for msg.select2
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public void setSelect2(String select2) {
        this.select2 = select2 == null ? null : select2.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg.create_at
     * @return  the value of msg.create_at
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg.create_at
     * @param createAt  the value for msg.create_at
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Msg other = (Msg) that;
        return (this.getId() == null ? other.getId() == null : this.getId()
                .equals(other.getId()))
                && (this.getSenderId() == null ? other.getSenderId() == null
                        : this.getSenderId().equals(other.getSenderId()))
                && (this.getCluId() == null ? other.getCluId() == null : this
                        .getCluId().equals(other.getCluId()))
                && (this.getMsgType() == null ? other.getMsgType() == null
                        : this.getMsgType().equals(other.getMsgType()))
                && (this.getContent() == null ? other.getContent() == null
                        : this.getContent().equals(other.getContent()))
                && (this.getContentType() == null ? other.getContentType() == null
                        : this.getContentType().equals(other.getContentType()))
                && (this.getUrl() == null ? other.getUrl() == null : this
                        .getUrl().equals(other.getUrl()))
                && (this.getStype() == null ? other.getStype() == null : this
                        .getStype().equals(other.getStype()))
                && (this.getSelect1() == null ? other.getSelect1() == null
                        : this.getSelect1().equals(other.getSelect1()))
                && (this.getSelect2() == null ? other.getSelect2() == null
                        : this.getSelect2().equals(other.getSelect2()))
                && (this.getCreateAt() == null ? other.getCreateAt() == null
                        : this.getCreateAt().equals(other.getCreateAt()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result
                + ((getSenderId() == null) ? 0 : getSenderId().hashCode());
        result = prime * result
                + ((getCluId() == null) ? 0 : getCluId().hashCode());
        result = prime * result
                + ((getMsgType() == null) ? 0 : getMsgType().hashCode());
        result = prime * result
                + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime
                * result
                + ((getContentType() == null) ? 0 : getContentType().hashCode());
        result = prime * result
                + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result
                + ((getStype() == null) ? 0 : getStype().hashCode());
        result = prime * result
                + ((getSelect1() == null) ? 0 : getSelect1().hashCode());
        result = prime * result
                + ((getSelect2() == null) ? 0 : getSelect2().hashCode());
        result = prime * result
                + ((getCreateAt() == null) ? 0 : getCreateAt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", senderId=").append(senderId);
        sb.append(", cluId=").append(cluId);
        sb.append(", msgType=").append(msgType);
        sb.append(", content=").append(content);
        sb.append(", contentType=").append(contentType);
        sb.append(", url=").append(url);
        sb.append(", stype=").append(stype);
        sb.append(", select1=").append(select1);
        sb.append(", select2=").append(select2);
        sb.append(", createAt=").append(createAt);
        sb.append("]");
        return sb.toString();
    }
}