package com.uxiaoxi.ym.appserver.db.msg.dto;

import java.io.Serializable;
import java.util.Date;

public class MsgAcc implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg_acc.id
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg_acc.msg_id
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    private Long msgId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg_acc.clu_id
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    private Long cluId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg_acc.acc_id
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    private Long accId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg_acc.selected
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    private Integer selected;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg_acc.received
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    private Long received;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg_acc.version
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    private Long version;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg_acc.create_at
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    private Date createAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg_acc.use_yn
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    private Boolean useYn;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table msg_acc
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg_acc.id
     * @return  the value of msg_acc.id
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg_acc.id
     * @param id  the value for msg_acc.id
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg_acc.msg_id
     * @return  the value of msg_acc.msg_id
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public Long getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg_acc.msg_id
     * @param msgId  the value for msg_acc.msg_id
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg_acc.clu_id
     * @return  the value of msg_acc.clu_id
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public Long getCluId() {
        return cluId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg_acc.clu_id
     * @param cluId  the value for msg_acc.clu_id
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public void setCluId(Long cluId) {
        this.cluId = cluId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg_acc.acc_id
     * @return  the value of msg_acc.acc_id
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public Long getAccId() {
        return accId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg_acc.acc_id
     * @param accId  the value for msg_acc.acc_id
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public void setAccId(Long accId) {
        this.accId = accId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg_acc.selected
     * @return  the value of msg_acc.selected
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public Integer getSelected() {
        return selected;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg_acc.selected
     * @param selected  the value for msg_acc.selected
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public void setSelected(Integer selected) {
        this.selected = selected;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg_acc.received
     * @return  the value of msg_acc.received
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public Long getReceived() {
        return received;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg_acc.received
     * @param received  the value for msg_acc.received
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public void setReceived(Long received) {
        this.received = received;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg_acc.version
     * @return  the value of msg_acc.version
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg_acc.version
     * @param version  the value for msg_acc.version
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg_acc.create_at
     * @return  the value of msg_acc.create_at
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg_acc.create_at
     * @param createAt  the value for msg_acc.create_at
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg_acc.use_yn
     * @return  the value of msg_acc.use_yn
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public Boolean getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg_acc.use_yn
     * @param useYn  the value for msg_acc.use_yn
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    public void setUseYn(Boolean useYn) {
        this.useYn = useYn;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MsgAcc other = (MsgAcc) that;
        return (this.getId() == null ? other.getId() == null : this.getId()
                .equals(other.getId()))
                && (this.getMsgId() == null ? other.getMsgId() == null : this
                        .getMsgId().equals(other.getMsgId()))
                && (this.getCluId() == null ? other.getCluId() == null : this
                        .getCluId().equals(other.getCluId()))
                && (this.getAccId() == null ? other.getAccId() == null : this
                        .getAccId().equals(other.getAccId()))
                && (this.getSelected() == null ? other.getSelected() == null
                        : this.getSelected().equals(other.getSelected()))
                && (this.getReceived() == null ? other.getReceived() == null
                        : this.getReceived().equals(other.getReceived()))
                && (this.getVersion() == null ? other.getVersion() == null
                        : this.getVersion().equals(other.getVersion()))
                && (this.getCreateAt() == null ? other.getCreateAt() == null
                        : this.getCreateAt().equals(other.getCreateAt()))
                && (this.getUseYn() == null ? other.getUseYn() == null : this
                        .getUseYn().equals(other.getUseYn()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result
                + ((getMsgId() == null) ? 0 : getMsgId().hashCode());
        result = prime * result
                + ((getCluId() == null) ? 0 : getCluId().hashCode());
        result = prime * result
                + ((getAccId() == null) ? 0 : getAccId().hashCode());
        result = prime * result
                + ((getSelected() == null) ? 0 : getSelected().hashCode());
        result = prime * result
                + ((getReceived() == null) ? 0 : getReceived().hashCode());
        result = prime * result
                + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result
                + ((getCreateAt() == null) ? 0 : getCreateAt().hashCode());
        result = prime * result
                + ((getUseYn() == null) ? 0 : getUseYn().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Sat Jan 30 20:07:20 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", msgId=").append(msgId);
        sb.append(", cluId=").append(cluId);
        sb.append(", accId=").append(accId);
        sb.append(", selected=").append(selected);
        sb.append(", received=").append(received);
        sb.append(", version=").append(version);
        sb.append(", createAt=").append(createAt);
        sb.append(", useYn=").append(useYn);
        sb.append("]");
        return sb.toString();
    }
}