package com.uxiaoxi.ym.appserver.db.msg.dto;

import java.io.Serializable;

public class MsgType implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg_type.id
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column msg_type.title
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg_type.id
     * @return  the value of msg_type.id
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg_type.id
     * @param id  the value for msg_type.id
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column msg_type.title
     * @return  the value of msg_type.title
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column msg_type.title
     * @param title  the value for msg_type.title
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MsgType other = (MsgType) that;
        return (this.getId() == null ? other.getId() == null : this.getId()
                .equals(other.getId()))
                && (this.getTitle() == null ? other.getTitle() == null : this
                        .getTitle().equals(other.getTitle()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result
                + ((getTitle() == null) ? 0 : getTitle().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append("]");
        return sb.toString();
    }
}