package com.uxiaoxi.ym.appserver.db.msg.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OfficialAccUserExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    public OfficialAccUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value,
                String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property
                        + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1,
                Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property
                        + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAccIdIsNull() {
            addCriterion("acc_id is null");
            return (Criteria) this;
        }

        public Criteria andAccIdIsNotNull() {
            addCriterion("acc_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccIdEqualTo(Long value) {
            addCriterion("acc_id =", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdNotEqualTo(Long value) {
            addCriterion("acc_id <>", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdGreaterThan(Long value) {
            addCriterion("acc_id >", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdGreaterThanOrEqualTo(Long value) {
            addCriterion("acc_id >=", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdLessThan(Long value) {
            addCriterion("acc_id <", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdLessThanOrEqualTo(Long value) {
            addCriterion("acc_id <=", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdIn(List<Long> values) {
            addCriterion("acc_id in", values, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdNotIn(List<Long> values) {
            addCriterion("acc_id not in", values, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdBetween(Long value1, Long value2) {
            addCriterion("acc_id between", value1, value2, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdNotBetween(Long value1, Long value2) {
            addCriterion("acc_id not between", value1, value2, "accId");
            return (Criteria) this;
        }

        public Criteria andOffAccIdIsNull() {
            addCriterion("off_acc_id is null");
            return (Criteria) this;
        }

        public Criteria andOffAccIdIsNotNull() {
            addCriterion("off_acc_id is not null");
            return (Criteria) this;
        }

        public Criteria andOffAccIdEqualTo(Long value) {
            addCriterion("off_acc_id =", value, "offAccId");
            return (Criteria) this;
        }

        public Criteria andOffAccIdNotEqualTo(Long value) {
            addCriterion("off_acc_id <>", value, "offAccId");
            return (Criteria) this;
        }

        public Criteria andOffAccIdGreaterThan(Long value) {
            addCriterion("off_acc_id >", value, "offAccId");
            return (Criteria) this;
        }

        public Criteria andOffAccIdGreaterThanOrEqualTo(Long value) {
            addCriterion("off_acc_id >=", value, "offAccId");
            return (Criteria) this;
        }

        public Criteria andOffAccIdLessThan(Long value) {
            addCriterion("off_acc_id <", value, "offAccId");
            return (Criteria) this;
        }

        public Criteria andOffAccIdLessThanOrEqualTo(Long value) {
            addCriterion("off_acc_id <=", value, "offAccId");
            return (Criteria) this;
        }

        public Criteria andOffAccIdIn(List<Long> values) {
            addCriterion("off_acc_id in", values, "offAccId");
            return (Criteria) this;
        }

        public Criteria andOffAccIdNotIn(List<Long> values) {
            addCriterion("off_acc_id not in", values, "offAccId");
            return (Criteria) this;
        }

        public Criteria andOffAccIdBetween(Long value1, Long value2) {
            addCriterion("off_acc_id between", value1, value2, "offAccId");
            return (Criteria) this;
        }

        public Criteria andOffAccIdNotBetween(Long value1, Long value2) {
            addCriterion("off_acc_id not between", value1, value2, "offAccId");
            return (Criteria) this;
        }

        public Criteria andMsgFlgIsNull() {
            addCriterion("msg_flg is null");
            return (Criteria) this;
        }

        public Criteria andMsgFlgIsNotNull() {
            addCriterion("msg_flg is not null");
            return (Criteria) this;
        }

        public Criteria andMsgFlgEqualTo(Long value) {
            addCriterion("msg_flg =", value, "msgFlg");
            return (Criteria) this;
        }

        public Criteria andMsgFlgNotEqualTo(Long value) {
            addCriterion("msg_flg <>", value, "msgFlg");
            return (Criteria) this;
        }

        public Criteria andMsgFlgGreaterThan(Long value) {
            addCriterion("msg_flg >", value, "msgFlg");
            return (Criteria) this;
        }

        public Criteria andMsgFlgGreaterThanOrEqualTo(Long value) {
            addCriterion("msg_flg >=", value, "msgFlg");
            return (Criteria) this;
        }

        public Criteria andMsgFlgLessThan(Long value) {
            addCriterion("msg_flg <", value, "msgFlg");
            return (Criteria) this;
        }

        public Criteria andMsgFlgLessThanOrEqualTo(Long value) {
            addCriterion("msg_flg <=", value, "msgFlg");
            return (Criteria) this;
        }

        public Criteria andMsgFlgIn(List<Long> values) {
            addCriterion("msg_flg in", values, "msgFlg");
            return (Criteria) this;
        }

        public Criteria andMsgFlgNotIn(List<Long> values) {
            addCriterion("msg_flg not in", values, "msgFlg");
            return (Criteria) this;
        }

        public Criteria andMsgFlgBetween(Long value1, Long value2) {
            addCriterion("msg_flg between", value1, value2, "msgFlg");
            return (Criteria) this;
        }

        public Criteria andMsgFlgNotBetween(Long value1, Long value2) {
            addCriterion("msg_flg not between", value1, value2, "msgFlg");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("create_at is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("create_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Date value) {
            addCriterion("create_at =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Date value) {
            addCriterion("create_at <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Date value) {
            addCriterion("create_at >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("create_at >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Date value) {
            addCriterion("create_at <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Date value) {
            addCriterion("create_at <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Date> values) {
            addCriterion("create_at in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Date> values) {
            addCriterion("create_at not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Date value1, Date value2) {
            addCriterion("create_at between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Date value1, Date value2) {
            addCriterion("create_at not between", value1, value2, "createAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table official_acc_user
     * @mbggenerated  Thu Feb 25 16:06:15 CST 2016
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue,
                String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table official_acc_user
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 17 19:19:26 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}