package com.uxiaoxi.ym.appserver.db.msg.dto;

import java.io.Serializable;
import java.util.Date;

public class OfficialAccounts implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_accounts.id
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_accounts.name
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_accounts.face
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    private String face;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_accounts.create_at
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_accounts.id
     *
     * @return the value of official_accounts.id
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_accounts.id
     *
     * @param id the value for official_accounts.id
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_accounts.name
     *
     * @return the value of official_accounts.name
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_accounts.name
     *
     * @param name the value for official_accounts.name
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_accounts.face
     *
     * @return the value of official_accounts.face
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_accounts.face
     *
     * @param face the value for official_accounts.face
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    public void setFace(String face) {
        this.face = face == null ? null : face.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_accounts.create_at
     *
     * @return the value of official_accounts.create_at
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_accounts.create_at
     *
     * @param createAt the value for official_accounts.create_at
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OfficialAccounts other = (OfficialAccounts) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getFace() == null ? other.getFace() == null : this.getFace().equals(other.getFace()))
            && (this.getCreateAt() == null ? other.getCreateAt() == null : this.getCreateAt().equals(other.getCreateAt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getFace() == null) ? 0 : getFace().hashCode());
        result = prime * result + ((getCreateAt() == null) ? 0 : getCreateAt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", face=").append(face);
        sb.append(", createAt=").append(createAt);
        sb.append("]");
        return sb.toString();
    }
}