package com.uxiaoxi.ym.appserver.db.msg.dto;

import java.io.Serializable;
import java.util.Date;

public class OfficialAccExplain implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_acc_explain.id
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_acc_explain.off_acc_id
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    private Long offAccId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_acc_explain.picture_url
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_acc_explain.explain
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    private String explain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_acc_explain.create_at
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table official_acc_explain
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_acc_explain.id
     *
     * @return the value of official_acc_explain.id
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_acc_explain.id
     *
     * @param id the value for official_acc_explain.id
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_acc_explain.off_acc_id
     *
     * @return the value of official_acc_explain.off_acc_id
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    public Long getOffAccId() {
        return offAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_acc_explain.off_acc_id
     *
     * @param offAccId the value for official_acc_explain.off_acc_id
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    public void setOffAccId(Long offAccId) {
        this.offAccId = offAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_acc_explain.picture_url
     *
     * @return the value of official_acc_explain.picture_url
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_acc_explain.picture_url
     *
     * @param pictureUrl the value for official_acc_explain.picture_url
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_acc_explain.explain
     *
     * @return the value of official_acc_explain.explain
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_acc_explain.explain
     *
     * @param explain the value for official_acc_explain.explain
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    public void setExplain(String explain) {
        this.explain = explain == null ? null : explain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column official_acc_explain.create_at
     *
     * @return the value of official_acc_explain.create_at
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column official_acc_explain.create_at
     *
     * @param createAt the value for official_acc_explain.create_at
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_explain
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OfficialAccExplain other = (OfficialAccExplain) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOffAccId() == null ? other.getOffAccId() == null : this.getOffAccId().equals(other.getOffAccId()))
            && (this.getPictureUrl() == null ? other.getPictureUrl() == null : this.getPictureUrl().equals(other.getPictureUrl()))
            && (this.getExplain() == null ? other.getExplain() == null : this.getExplain().equals(other.getExplain()))
            && (this.getCreateAt() == null ? other.getCreateAt() == null : this.getCreateAt().equals(other.getCreateAt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_explain
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOffAccId() == null) ? 0 : getOffAccId().hashCode());
        result = prime * result + ((getPictureUrl() == null) ? 0 : getPictureUrl().hashCode());
        result = prime * result + ((getExplain() == null) ? 0 : getExplain().hashCode());
        result = prime * result + ((getCreateAt() == null) ? 0 : getCreateAt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_explain
     *
     * @mbggenerated Mon Feb 22 16:29:57 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", offAccId=").append(offAccId);
        sb.append(", pictureUrl=").append(pictureUrl);
        sb.append(", explain=").append(explain);
        sb.append(", createAt=").append(createAt);
        sb.append("]");
        return sb.toString();
    }
}