package com.uxiaoxi.ym.appserver.db.msg.dto;

import java.io.Serializable;
import java.util.Date;

public class OptionLog implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column option_log.id
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column option_log.option_type
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    private String optionType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column option_log.data_id
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    private Long dataId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column option_log.create_at
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    private Date createAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column option_log.data_after
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    private String dataAfter;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table option_log
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column option_log.id
     * @return  the value of option_log.id
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column option_log.id
     * @param id  the value for option_log.id
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column option_log.option_type
     * @return  the value of option_log.option_type
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    public String getOptionType() {
        return optionType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column option_log.option_type
     * @param optionType  the value for option_log.option_type
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    public void setOptionType(String optionType) {
        this.optionType = optionType == null ? null : optionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column option_log.data_id
     * @return  the value of option_log.data_id
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    public Long getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column option_log.data_id
     * @param dataId  the value for option_log.data_id
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    public void setDataId(Long dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column option_log.create_at
     * @return  the value of option_log.create_at
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column option_log.create_at
     * @param createAt  the value for option_log.create_at
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column option_log.data_after
     * @return  the value of option_log.data_after
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    public String getDataAfter() {
        return dataAfter;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column option_log.data_after
     * @param dataAfter  the value for option_log.data_after
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    public void setDataAfter(String dataAfter) {
        this.dataAfter = dataAfter == null ? null : dataAfter.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table option_log
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OptionLog other = (OptionLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId()
                .equals(other.getId()))
                && (this.getOptionType() == null ? other.getOptionType() == null
                        : this.getOptionType().equals(other.getOptionType()))
                && (this.getDataId() == null ? other.getDataId() == null : this
                        .getDataId().equals(other.getDataId()))
                && (this.getCreateAt() == null ? other.getCreateAt() == null
                        : this.getCreateAt().equals(other.getCreateAt()))
                && (this.getDataAfter() == null ? other.getDataAfter() == null
                        : this.getDataAfter().equals(other.getDataAfter()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table option_log
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result
                + ((getOptionType() == null) ? 0 : getOptionType().hashCode());
        result = prime * result
                + ((getDataId() == null) ? 0 : getDataId().hashCode());
        result = prime * result
                + ((getCreateAt() == null) ? 0 : getCreateAt().hashCode());
        result = prime * result
                + ((getDataAfter() == null) ? 0 : getDataAfter().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table option_log
     * @mbggenerated  Sat Jan 30 20:32:53 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", optionType=").append(optionType);
        sb.append(", dataId=").append(dataId);
        sb.append(", createAt=").append(createAt);
        sb.append(", dataAfter=").append(dataAfter);
        sb.append("]");
        return sb.toString();
    }
}