package com.uxiaoxi.ym.appserver.db.account.dto;

import java.io.Serializable;
import java.util.Date;

public class Account implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.id
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.phone
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private String phone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.password
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.type
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private Integer type;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.name
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.sex
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private Integer sex;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.face
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private String face;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.token
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private String token;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.regid
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private String regid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.version
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private String version;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.create_dt
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private Date createDt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.msg_switch
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private Integer msgSwitch;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.msg_vs
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private Long msgVs;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table account
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.id
     * @return  the value of account.id
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.id
     * @param id  the value for account.id
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.phone
     * @return  the value of account.phone
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.phone
     * @param phone  the value for account.phone
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.password
     * @return  the value of account.password
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.password
     * @param password  the value for account.password
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.type
     * @return  the value of account.type
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.type
     * @param type  the value for account.type
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.name
     * @return  the value of account.name
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.name
     * @param name  the value for account.name
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.sex
     * @return  the value of account.sex
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.sex
     * @param sex  the value for account.sex
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.face
     * @return  the value of account.face
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.face
     * @param face  the value for account.face
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public void setFace(String face) {
        this.face = face == null ? null : face.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.token
     * @return  the value of account.token
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.token
     * @param token  the value for account.token
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.regid
     * @return  the value of account.regid
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public String getRegid() {
        return regid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.regid
     * @param regid  the value for account.regid
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public void setRegid(String regid) {
        this.regid = regid == null ? null : regid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.version
     * @return  the value of account.version
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.version
     * @param version  the value for account.version
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.create_dt
     * @return  the value of account.create_dt
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.create_dt
     * @param createDt  the value for account.create_dt
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.msg_switch
     * @return  the value of account.msg_switch
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public Integer getMsgSwitch() {
        return msgSwitch;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.msg_switch
     * @param msgSwitch  the value for account.msg_switch
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public void setMsgSwitch(Integer msgSwitch) {
        this.msgSwitch = msgSwitch;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.msg_vs
     * @return  the value of account.msg_vs
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public Long getMsgVs() {
        return msgVs;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.msg_vs
     * @param msgVs  the value for account.msg_vs
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    public void setMsgVs(Long msgVs) {
        this.msgVs = msgVs;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table account
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Account other = (Account) that;
        return (this.getId() == null ? other.getId() == null : this.getId()
                .equals(other.getId()))
                && (this.getPhone() == null ? other.getPhone() == null : this
                        .getPhone().equals(other.getPhone()))
                && (this.getPassword() == null ? other.getPassword() == null
                        : this.getPassword().equals(other.getPassword()))
                && (this.getType() == null ? other.getType() == null : this
                        .getType().equals(other.getType()))
                && (this.getName() == null ? other.getName() == null : this
                        .getName().equals(other.getName()))
                && (this.getSex() == null ? other.getSex() == null : this
                        .getSex().equals(other.getSex()))
                && (this.getFace() == null ? other.getFace() == null : this
                        .getFace().equals(other.getFace()))
                && (this.getToken() == null ? other.getToken() == null : this
                        .getToken().equals(other.getToken()))
                && (this.getRegid() == null ? other.getRegid() == null : this
                        .getRegid().equals(other.getRegid()))
                && (this.getVersion() == null ? other.getVersion() == null
                        : this.getVersion().equals(other.getVersion()))
                && (this.getCreateDt() == null ? other.getCreateDt() == null
                        : this.getCreateDt().equals(other.getCreateDt()))
                && (this.getMsgSwitch() == null ? other.getMsgSwitch() == null
                        : this.getMsgSwitch().equals(other.getMsgSwitch()))
                && (this.getMsgVs() == null ? other.getMsgVs() == null : this
                        .getMsgVs().equals(other.getMsgVs()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table account
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result
                + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result
                + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result
                + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result
                + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result
                + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result
                + ((getFace() == null) ? 0 : getFace().hashCode());
        result = prime * result
                + ((getToken() == null) ? 0 : getToken().hashCode());
        result = prime * result
                + ((getRegid() == null) ? 0 : getRegid().hashCode());
        result = prime * result
                + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result
                + ((getCreateDt() == null) ? 0 : getCreateDt().hashCode());
        result = prime * result
                + ((getMsgSwitch() == null) ? 0 : getMsgSwitch().hashCode());
        result = prime * result
                + ((getMsgVs() == null) ? 0 : getMsgVs().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table account
     * @mbggenerated  Wed Jan 27 11:03:30 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", phone=").append(phone);
        sb.append(", password=").append(password);
        sb.append(", type=").append(type);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", face=").append(face);
        sb.append(", token=").append(token);
        sb.append(", regid=").append(regid);
        sb.append(", version=").append(version);
        sb.append(", createDt=").append(createDt);
        sb.append(", msgSwitch=").append(msgSwitch);
        sb.append(", msgVs=").append(msgVs);
        sb.append("]");
        return sb.toString();
    }
}