package com.uxiaoxi.ym.appserver.db.version.mapper;

import com.uxiaoxi.ym.appserver.db.version.dto.VersionMng;
import com.uxiaoxi.ym.appserver.db.version.dto.VersionMngExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VersionMngMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    int countByExample(VersionMngExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    int deleteByExample(VersionMngExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    int insert(VersionMng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    int insertSelective(VersionMng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    List<VersionMng> selectByExample(VersionMngExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    VersionMng selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    int updateByExampleSelective(@Param("record") VersionMng record, @Param("example") VersionMngExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    int updateByExample(@Param("record") VersionMng record, @Param("example") VersionMngExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    int updateByPrimaryKeySelective(VersionMng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    int updateByPrimaryKey(VersionMng record);
}