package com.uxiaoxi.ym.appserver.db.cluster.mapper;

import com.uxiaoxi.ym.appserver.db.cluster.dto.Children;
import com.uxiaoxi.ym.appserver.db.cluster.dto.ChildrenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChildrenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table children
     *
     * @mbggenerated Wed Jan 27 10:11:11 CST 2016
     */
    int countByExample(ChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table children
     *
     * @mbggenerated Wed Jan 27 10:11:11 CST 2016
     */
    int deleteByExample(ChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table children
     *
     * @mbggenerated Wed Jan 27 10:11:11 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table children
     *
     * @mbggenerated Wed Jan 27 10:11:11 CST 2016
     */
    int insert(Children record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table children
     *
     * @mbggenerated Wed Jan 27 10:11:11 CST 2016
     */
    int insertSelective(Children record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table children
     *
     * @mbggenerated Wed Jan 27 10:11:11 CST 2016
     */
    List<Children> selectByExample(ChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table children
     *
     * @mbggenerated Wed Jan 27 10:11:11 CST 2016
     */
    Children selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table children
     *
     * @mbggenerated Wed Jan 27 10:11:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") Children record, @Param("example") ChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table children
     *
     * @mbggenerated Wed Jan 27 10:11:11 CST 2016
     */
    int updateByExample(@Param("record") Children record, @Param("example") ChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table children
     *
     * @mbggenerated Wed Jan 27 10:11:11 CST 2016
     */
    int updateByPrimaryKeySelective(Children record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table children
     *
     * @mbggenerated Wed Jan 27 10:11:11 CST 2016
     */
    int updateByPrimaryKey(Children record);
}