package com.uxiaoxi.ym.appserver.db.cluster.mapper;

import com.uxiaoxi.ym.appserver.db.cluster.dto.Cluster;
import com.uxiaoxi.ym.appserver.db.cluster.dto.ClusterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClusterMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Wed Jan 27 11:05:33 CST 2016
     */
    int countByExample(ClusterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Wed Jan 27 11:05:33 CST 2016
     */
    int deleteByExample(ClusterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Wed Jan 27 11:05:33 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Wed Jan 27 11:05:33 CST 2016
     */
    int insert(Cluster record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Wed Jan 27 11:05:33 CST 2016
     */
    int insertSelective(Cluster record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Wed Jan 27 11:05:33 CST 2016
     */
    List<Cluster> selectByExample(ClusterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Wed Jan 27 11:05:33 CST 2016
     */
    Cluster selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Wed Jan 27 11:05:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") Cluster record,
            @Param("example") ClusterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Wed Jan 27 11:05:33 CST 2016
     */
    int updateByExample(@Param("record") Cluster record,
            @Param("example") ClusterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Wed Jan 27 11:05:33 CST 2016
     */
    int updateByPrimaryKeySelective(Cluster record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Wed Jan 27 11:05:33 CST 2016
     */
    int updateByPrimaryKey(Cluster record);
}