package com.uxiaoxi.ym.appserver.db.cluster.mapper;

import com.uxiaoxi.ym.appserver.db.cluster.dto.Cluster;
import com.uxiaoxi.ym.appserver.db.cluster.dto.ClusterExample;
import com.uxiaoxi.ym.appserver.web.cluster.form.ClusterSearchBySnForm;
import com.uxiaoxi.ym.appserver.web.cluster.vo.ClusterBySnResult;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ClusterMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Mon Feb 01 18:04:10 CST 2016
     */
    int countByExample(ClusterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Mon Feb 01 18:04:10 CST 2016
     */
    int deleteByExample(ClusterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Mon Feb 01 18:04:10 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Mon Feb 01 18:04:10 CST 2016
     */
    int insert(Cluster record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Mon Feb 01 18:04:10 CST 2016
     */
    int insertSelective(Cluster record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Mon Feb 01 18:04:10 CST 2016
     */
    List<Cluster> selectByExample(ClusterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Mon Feb 01 18:04:10 CST 2016
     */
    Cluster selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Mon Feb 01 18:04:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") Cluster record,
            @Param("example") ClusterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Mon Feb 01 18:04:10 CST 2016
     */
    int updateByExample(@Param("record") Cluster record,
            @Param("example") ClusterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Mon Feb 01 18:04:10 CST 2016
     */
    int updateByPrimaryKeySelective(Cluster record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster
     * @mbggenerated  Mon Feb 01 18:04:10 CST 2016
     */
    int updateByPrimaryKey(Cluster record);

    /**
     * @param map
     * @return
     */
    int countUserByType(Map<String,Object> map);
    
    /**
     * @param form
     * @return
     */
    ClusterBySnResult searchBySn(ClusterSearchBySnForm form);
    
    /**
     * @param
     * @return
     */
    int searchMaxSn();
}