package com.uxiaoxi.ym.appserver.db.cluster.mapper;

import com.uxiaoxi.ym.appserver.db.cluster.dto.ClusterUser;
import com.uxiaoxi.ym.appserver.db.cluster.dto.ClusterUserExample;
import com.uxiaoxi.ym.appserver.web.cluster.form.ClusterUserListForm;
import com.uxiaoxi.ym.appserver.web.cluster.form.ClusterUserSearchForm;
import com.uxiaoxi.ym.appserver.web.cluster.vo.ClusterUserListVO;
import com.uxiaoxi.ym.appserver.web.cluster.vo.ClusterUserSearchResultVO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ClusterUserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Jan 27 11:06:29 CST 2016
     */
    int countByExample(ClusterUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Jan 27 11:06:29 CST 2016
     */
    int deleteByExample(ClusterUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Jan 27 11:06:29 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Jan 27 11:06:29 CST 2016
     */
    int insert(ClusterUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Jan 27 11:06:29 CST 2016
     */
    int insertSelective(ClusterUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Jan 27 11:06:29 CST 2016
     */
    List<ClusterUser> selectByExample(ClusterUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Jan 27 11:06:29 CST 2016
     */
    ClusterUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Jan 27 11:06:29 CST 2016
     */
    int updateByExampleSelective(@Param("record") ClusterUser record,
            @Param("example") ClusterUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Jan 27 11:06:29 CST 2016
     */
    int updateByExample(@Param("record") ClusterUser record,
            @Param("example") ClusterUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Jan 27 11:06:29 CST 2016
     */
    int updateByPrimaryKeySelective(ClusterUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cluster_user
     * @mbggenerated  Wed Jan 27 11:06:29 CST 2016
     */
    int updateByPrimaryKey(ClusterUser record);
    
    List<ClusterUserSearchResultVO> searchByUid(ClusterUserSearchForm form);
    
    List<ClusterUserListVO> searchByGid(ClusterUserListForm form);
    
    List<ClusterUser> getAllByUid(Long id);
}