package com.uxiaoxi.ym.appserver.db.cluster.mapper;

import com.uxiaoxi.ym.appserver.db.cluster.dto.Remark;
import com.uxiaoxi.ym.appserver.db.cluster.dto.RemarkExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RemarkMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 20:07:46 CST 2016
     */
    int countByExample(RemarkExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 20:07:46 CST 2016
     */
    int deleteByExample(RemarkExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 20:07:46 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 20:07:46 CST 2016
     */
    int insert(Remark record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 20:07:46 CST 2016
     */
    int insertSelective(Remark record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 20:07:46 CST 2016
     */
    List<Remark> selectByExample(RemarkExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 20:07:46 CST 2016
     */
    Remark selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 20:07:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") Remark record,
            @Param("example") RemarkExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 20:07:46 CST 2016
     */
    int updateByExample(@Param("record") Remark record,
            @Param("example") RemarkExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 20:07:46 CST 2016
     */
    int updateByPrimaryKeySelective(Remark record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table remark
     * @mbggenerated  Sat Jan 30 20:07:46 CST 2016
     */
    int updateByPrimaryKey(Remark record);

    /**
     * @param
     * @return
     */
    String selectRemark(RemarkExample example);
}