package com.uxiaoxi.ym.appserver.db.verification.mapper;

import com.uxiaoxi.ym.appserver.db.verification.dto.VerificationCode;
import com.uxiaoxi.ym.appserver.db.verification.dto.VerificationCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VerificationCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbggenerated Wed Jan 27 10:54:31 CST 2016
     */
    int countByExample(VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbggenerated Wed Jan 27 10:54:31 CST 2016
     */
    int deleteByExample(VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbggenerated Wed Jan 27 10:54:31 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbggenerated Wed Jan 27 10:54:31 CST 2016
     */
    int insert(VerificationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbggenerated Wed Jan 27 10:54:31 CST 2016
     */
    int insertSelective(VerificationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbggenerated Wed Jan 27 10:54:31 CST 2016
     */
    List<VerificationCode> selectByExample(VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbggenerated Wed Jan 27 10:54:31 CST 2016
     */
    VerificationCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbggenerated Wed Jan 27 10:54:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") VerificationCode record, @Param("example") VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbggenerated Wed Jan 27 10:54:31 CST 2016
     */
    int updateByExample(@Param("record") VerificationCode record, @Param("example") VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbggenerated Wed Jan 27 10:54:31 CST 2016
     */
    int updateByPrimaryKeySelective(VerificationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbggenerated Wed Jan 27 10:54:31 CST 2016
     */
    int updateByPrimaryKey(VerificationCode record);
}