package com.uxiaoxi.ym.appserver.db.msg.mapper;

import com.uxiaoxi.ym.appserver.db.msg.dto.MsgAcc;
import com.uxiaoxi.ym.appserver.db.msg.dto.MsgAccExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgAccMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Wed Jan 27 11:11:31 CST 2016
     */
    int countByExample(MsgAccExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Wed Jan 27 11:11:31 CST 2016
     */
    int deleteByExample(MsgAccExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Wed Jan 27 11:11:31 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Wed Jan 27 11:11:31 CST 2016
     */
    int insert(MsgAcc record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Wed Jan 27 11:11:31 CST 2016
     */
    int insertSelective(MsgAcc record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Wed Jan 27 11:11:31 CST 2016
     */
    List<MsgAcc> selectByExample(MsgAccExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Wed Jan 27 11:11:31 CST 2016
     */
    MsgAcc selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Wed Jan 27 11:11:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") MsgAcc record,
            @Param("example") MsgAccExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Wed Jan 27 11:11:31 CST 2016
     */
    int updateByExample(@Param("record") MsgAcc record,
            @Param("example") MsgAccExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Wed Jan 27 11:11:31 CST 2016
     */
    int updateByPrimaryKeySelective(MsgAcc record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_acc
     * @mbggenerated  Wed Jan 27 11:11:31 CST 2016
     */
    int updateByPrimaryKey(MsgAcc record);
}