package com.uxiaoxi.ym.appserver.db.msg.mapper;

import com.uxiaoxi.ym.appserver.db.msg.dto.Msg;
import com.uxiaoxi.ym.appserver.db.msg.dto.MsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    int countByExample(MsgExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    int deleteByExample(MsgExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    int insert(Msg record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    int insertSelective(Msg record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    List<Msg> selectByExample(MsgExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    Msg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") Msg record,
            @Param("example") MsgExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    int updateByExample(@Param("record") Msg record,
            @Param("example") MsgExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    int updateByPrimaryKeySelective(Msg record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg
     * @mbggenerated  Thu Jan 28 16:48:59 CST 2016
     */
    int updateByPrimaryKey(Msg record);
}