package com.uxiaoxi.ym.appserver.db.msg.mapper;

import com.uxiaoxi.ym.appserver.db.msg.dto.MsgType;
import com.uxiaoxi.ym.appserver.db.msg.dto.MsgTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgTypeMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    int countByExample(MsgTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    int deleteByExample(MsgTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    int insert(MsgType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    int insertSelective(MsgType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    List<MsgType> selectByExample(MsgTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    MsgType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") MsgType record,
            @Param("example") MsgTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    int updateByExample(@Param("record") MsgType record,
            @Param("example") MsgTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    int updateByPrimaryKeySelective(MsgType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table msg_type
     * @mbggenerated  Wed Jan 27 11:18:38 CST 2016
     */
    int updateByPrimaryKey(MsgType record);
}