package com.uxiaoxi.ym.appserver.db.msg.mapper;

import com.uxiaoxi.ym.appserver.db.msg.dto.OfficialAccUser;
import com.uxiaoxi.ym.appserver.db.msg.dto.OfficialAccUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfficialAccUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_user
     *
     * @mbggenerated Wed Feb 17 19:19:26 CST 2016
     */
    int countByExample(OfficialAccUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_user
     *
     * @mbggenerated Wed Feb 17 19:19:26 CST 2016
     */
    int deleteByExample(OfficialAccUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_user
     *
     * @mbggenerated Wed Feb 17 19:19:26 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_user
     *
     * @mbggenerated Wed Feb 17 19:19:26 CST 2016
     */
    int insert(OfficialAccUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_user
     *
     * @mbggenerated Wed Feb 17 19:19:26 CST 2016
     */
    int insertSelective(OfficialAccUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_user
     *
     * @mbggenerated Wed Feb 17 19:19:26 CST 2016
     */
    List<OfficialAccUser> selectByExample(OfficialAccUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_user
     *
     * @mbggenerated Wed Feb 17 19:19:26 CST 2016
     */
    OfficialAccUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_user
     *
     * @mbggenerated Wed Feb 17 19:19:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") OfficialAccUser record, @Param("example") OfficialAccUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_user
     *
     * @mbggenerated Wed Feb 17 19:19:26 CST 2016
     */
    int updateByExample(@Param("record") OfficialAccUser record, @Param("example") OfficialAccUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_user
     *
     * @mbggenerated Wed Feb 17 19:19:26 CST 2016
     */
    int updateByPrimaryKeySelective(OfficialAccUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_acc_user
     *
     * @mbggenerated Wed Feb 17 19:19:26 CST 2016
     */
    int updateByPrimaryKey(OfficialAccUser record);
}