package com.uxiaoxi.ym.appserver.db.msg.mapper;

import com.uxiaoxi.ym.appserver.db.msg.dto.OfficialAccounts;
import com.uxiaoxi.ym.appserver.db.msg.dto.OfficialAccountsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfficialAccountsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    int countByExample(OfficialAccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    int deleteByExample(OfficialAccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    int insert(OfficialAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    int insertSelective(OfficialAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    List<OfficialAccounts> selectByExample(OfficialAccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    OfficialAccounts selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") OfficialAccounts record, @Param("example") OfficialAccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    int updateByExample(@Param("record") OfficialAccounts record, @Param("example") OfficialAccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    int updateByPrimaryKeySelective(OfficialAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_accounts
     *
     * @mbggenerated Wed Feb 17 19:22:39 CST 2016
     */
    int updateByPrimaryKey(OfficialAccounts record);
}