package com.uxiaoxi.ym.appserver.db.version.dto;

import java.io.Serializable;
import java.util.Date;

public class VersionMng implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_mng.id
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_mng.version
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_mng.version_name
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    private String versionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_mng.url
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_mng.os_type
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    private Integer osType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_mng.create_dt
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_mng.id
     *
     * @return the value of version_mng.id
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_mng.id
     *
     * @param id the value for version_mng.id
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_mng.version
     *
     * @return the value of version_mng.version
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_mng.version
     *
     * @param version the value for version_mng.version
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_mng.version_name
     *
     * @return the value of version_mng.version_name
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    public String getVersionName() {
        return versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_mng.version_name
     *
     * @param versionName the value for version_mng.version_name
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    public void setVersionName(String versionName) {
        this.versionName = versionName == null ? null : versionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_mng.url
     *
     * @return the value of version_mng.url
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_mng.url
     *
     * @param url the value for version_mng.url
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_mng.os_type
     *
     * @return the value of version_mng.os_type
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    public Integer getOsType() {
        return osType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_mng.os_type
     *
     * @param osType the value for version_mng.os_type
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    public void setOsType(Integer osType) {
        this.osType = osType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_mng.create_dt
     *
     * @return the value of version_mng.create_dt
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_mng.create_dt
     *
     * @param createDt the value for version_mng.create_dt
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VersionMng other = (VersionMng) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getVersionName() == null ? other.getVersionName() == null : this.getVersionName().equals(other.getVersionName()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getOsType() == null ? other.getOsType() == null : this.getOsType().equals(other.getOsType()))
            && (this.getCreateDt() == null ? other.getCreateDt() == null : this.getCreateDt().equals(other.getCreateDt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getVersionName() == null) ? 0 : getVersionName().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getOsType() == null) ? 0 : getOsType().hashCode());
        result = prime * result + ((getCreateDt() == null) ? 0 : getCreateDt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_mng
     *
     * @mbggenerated Wed Jan 27 10:53:56 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", version=").append(version);
        sb.append(", versionName=").append(versionName);
        sb.append(", url=").append(url);
        sb.append(", osType=").append(osType);
        sb.append(", createDt=").append(createDt);
        sb.append("]");
        return sb.toString();
    }
}